# Generated by Django 2.2.5 on 2020-01-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ng_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(default='no description provided', max_length=500)),
                ('donations', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('website', models.CharField(max_length=250)),
                ('stats', models.ImageField(upload_to='images/ngo')),
            ],
        ),
    ]
